export const sampleData = {
  bidang: [
    {
      id: 1,
      nama: "Bidang Kepemimpinan",
      deskripsi: "Bertanggung jawab atas koordinasi dan kepemimpinan organisasi OSIS",
      fotoBersama: "/osis-leadership-team-group-photo.jpg",
      anggota: [
        {
          id: 1,
          nama: "Ahmad Rizki",
          role: "Ketua OSIS",
          foto: "/indonesian-student-leader-portrait.jpg",
          deskripsi:
            "Memimpin seluruh kegiatan OSIS dan mengkoordinasikan semua seksi bidang untuk mencapai visi misi organisasi.",
          kontak: "ahmad.rizki@armata.sch.id",
        },
        {
          id: 2,
          nama: "Siti Nurhaliza",
          role: "Wakil Ketua OSIS",
          foto: "/indonesian-female-student-leader-portrait.jpg",
          deskripsi:
            "Membantu ketua dalam menjalankan program kerja dan mengawasi pelaksanaan kegiatan di setiap seksi.",
          kontak: "siti.nurhaliza@armata.sch.id",
        },
        {
          id: 3,
          nama: "Budi Santoso",
          role: "Sekretaris",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Mengelola administrasi, dokumentasi, dan surat menyurat organisasi OSIS Armata.",
          kontak: "budi.santoso@armata.sch.id",
        },
        {
          id: 4,
          nama: "Dewi Lestari",
          role: "Bendahara",
          foto: "/indonesian-female-student-treasurer-portrait.jpg",
          deskripsi:
            "Mengelola keuangan organisasi dan memastikan transparansi dalam setiap pengeluaran dana kegiatan.",
          kontak: "dewi.lestari@armata.sch.id",
        },
      ],
    },
    {
      id: 2,
      nama: "Bidang Acara & Publikasi",
      deskripsi: "Mengelola perencanaan acara dan publikasi kegiatan OSIS",
      fotoBersama: "/osis-events-publication-team-group-photo.jpg",
      anggota: [
        {
          id: 5,
          nama: "Andi Pratama",
          role: "Koordinator Acara",
          foto: "/indonesian-student-event-coordinator-portrait.jpg",
          deskripsi: "Merencanakan dan mengkoordinasikan seluruh acara dan kegiatan yang diselenggarakan OSIS.",
          kontak: "andi.pratama@armata.sch.id",
        },
        {
          id: 6,
          nama: "Maya Sari",
          role: "Humas & Publikasi",
          foto: "/indonesian-female-student-public-relations-portrai.jpg",
          deskripsi: "Mengelola hubungan masyarakat, media sosial, dan publikasi kegiatan OSIS Armata.",
          kontak: "maya.sari@armata.sch.id",
        },
        {
          id: 7,
          nama: "Reza Firmansyah",
          role: "Koordinator Media",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Mengelola konten media sosial dan dokumentasi visual kegiatan OSIS.",
          kontak: "reza.firmansyah@armata.sch.id",
        },
        {
          id: 8,
          nama: "Indira Putri",
          role: "Desainer Grafis",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Membuat desain poster, banner, dan materi visual untuk kegiatan OSIS.",
          kontak: "indira.putri@armata.sch.id",
        },
      ],
    },
    {
      id: 3,
      nama: "Bidang Pengembangan Siswa",
      deskripsi: "Fokus pada pengembangan bakat dan minat siswa",
      fotoBersama: "/osis-student-development-team-group-photo.jpg",
      anggota: [
        {
          id: 9,
          nama: "Fajar Nugroho",
          role: "Koordinator Olahraga",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Mengorganisir kegiatan olahraga dan kompetisi antar kelas untuk siswa.",
          kontak: "fajar.nugroho@armata.sch.id",
        },
        {
          id: 10,
          nama: "Laila Sari",
          role: "Koordinator Seni",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Mengelola kegiatan seni dan budaya serta mengembangkan kreativitas siswa.",
          kontak: "laila.sari@armata.sch.id",
        },
        {
          id: 11,
          nama: "Dimas Pratama",
          role: "Koordinator Akademik",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Mengkoordinasikan program-program peningkatan prestasi akademik siswa.",
          kontak: "dimas.pratama@armata.sch.id",
        },
        {
          id: 12,
          nama: "Rina Maharani",
          role: "Koordinator Ekstrakurikuler",
          foto: "/placeholder-nkr8y.png",
          deskripsi: "Mengelola dan mengembangkan berbagai kegiatan ekstrakurikuler sekolah.",
          kontak: "rina.maharani@armata.sch.id",
        },
      ],
    },
  ],
  sekbid: [
    {
      id: 1,
      nama: "Ahmad Rizki",
      role: "Ketua OSIS",
      foto: "/indonesian-student-leader-portrait.jpg",
      deskripsi:
        "Memimpin seluruh kegiatan OSIS dan mengkoordinasikan semua seksi bidang untuk mencapai visi misi organisasi.",
      kontak: "ahmad.rizki@armata.sch.id",
    },
    {
      id: 2,
      nama: "Siti Nurhaliza",
      role: "Wakil Ketua OSIS",
      foto: "/indonesian-female-student-leader-portrait.jpg",
      deskripsi: "Membantu ketua dalam menjalankan program kerja dan mengawasi pelaksanaan kegiatan di setiap seksi.",
      kontak: "siti.nurhaliza@armata.sch.id",
    },
    {
      id: 3,
      nama: "Budi Santoso",
      role: "Sekretaris",
      foto: "/placeholder-nkr8y.png",
      deskripsi: "Mengelola administrasi, dokumentasi, dan surat menyurat organisasi OSIS Armata.",
      kontak: "budi.santoso@armata.sch.id",
    },
    {
      id: 4,
      nama: "Dewi Lestari",
      role: "Bendahara",
      foto: "/indonesian-female-student-treasurer-portrait.jpg",
      deskripsi: "Mengelola keuangan organisasi dan memastikan transparansi dalam setiap pengeluaran dana kegiatan.",
      kontak: "dewi.lestari@armata.sch.id",
    },
    {
      id: 5,
      nama: "Andi Pratama",
      role: "Koordinator Acara",
      foto: "/indonesian-student-event-coordinator-portrait.jpg",
      deskripsi: "Merencanakan dan mengkoordinasikan seluruh acara dan kegiatan yang diselenggarakan OSIS.",
      kontak: "andi.pratama@armata.sch.id",
    },
    {
      id: 6,
      nama: "Maya Sari",
      role: "Humas & Publikasi",
      foto: "/indonesian-female-student-public-relations-portrai.jpg",
      deskripsi: "Mengelola hubungan masyarakat, media sosial, dan publikasi kegiatan OSIS Armata.",
      kontak: "maya.sari@armata.sch.id",
    },
  ],
  kegiatan: [
    {
      id: 1,
      judul: "Masa Pengenalan Lingkungan Sekolah",
      deskripsi: "Kegiatan orientasi untuk siswa baru agar dapat beradaptasi dengan lingkungan sekolah",
      foto: "/placeholder-edxcv.png",
      tanggal: "Juli 2024",
    },
    {
      id: 2,
      judul: "Pekan Olahraga dan Seni",
      deskripsi: "Kompetisi olahraga dan seni antar kelas untuk mengembangkan bakat siswa",
      foto: "/placeholder-vr68j.png",
      tanggal: "Agustus 2024",
    },
    {
      id: 3,
      judul: "Bakti Sosial Lingkungan",
      deskripsi: "Kegiatan peduli lingkungan dengan membersihkan area sekitar sekolah",
      foto: "/placeholder-vbdjx.png",
      tanggal: "September 2024",
    },
    {
      id: 4,
      judul: "Festival Budaya Nusantara",
      deskripsi: "Pameran dan pertunjukan budaya daerah untuk melestarikan warisan Indonesia",
      foto: "/indonesian-cultural-festival-traditional-dance.jpg",
      tanggal: "Oktober 2024",
    },
    {
      id: 5,
      judul: "Seminar Motivasi Belajar",
      deskripsi: "Seminar dengan pembicara inspiratif untuk meningkatkan semangat belajar siswa",
      foto: "/indonesian-students-studying-together-library.jpg",
      tanggal: "November 2024",
    },
    {
      id: 6,
      judul: "Pentas Seni Akhir Tahun",
      deskripsi: "Pertunjukan seni dari berbagai ekstrakurikuler sebagai penutup tahun ajaran",
      foto: "/placeholder-3t5rj.png",
      tanggal: "Desember 2024",
    },
  ],
  galeri: [
    "/placeholder-v9d98.png",
    "/placeholder-ms3qh.png",
    "/indonesian-students-studying-together-library.jpg",
    "/placeholder-3t5rj.png",
    "/placeholder.svg?height=600&width=400",
    "/placeholder.svg?height=400&width=600",
    "/placeholder.svg?height=300&width=600",
    "/placeholder.svg?height=500&width=500",
  ],
  alumni: {
    id: [
      "Sebagai alumni OSIS Armata, saya bangga melihat perkembangan organisasi ini. Pengalaman di OSIS mengajarkan saya kepemimpinan dan kerja sama tim.",
      "OSIS Armata telah membentuk karakter saya menjadi lebih bertanggung jawab dan peduli terhadap sesama. Terima kasih untuk semua pengalaman berharga.",
      "Menjadi bagian dari OSIS Armata adalah kebanggaan tersendiri. Organisasi ini mengajarkan nilai-nilai luhur dan semangat gotong royong.",
    ],
    ar: [
      "كخريج من OSIS Armata، أنا فخور برؤية تطور هذه المنظمة. علمتني تجربة OSIS القيادة والعمل الجماعي.",
      "شكلت OSIS Armata شخصيتي لأصبح أكثر مسؤولية واهتمامًا بالآخرين. شكراً لجميع التجارب القيمة.",
      "كوني جزءًا من OSIS Armata فخر خاص. هذه المنظمة تعلم القيم النبيلة وروح التعاون.",
    ],
    en: [
      "As an OSIS Armata alumni, I'm proud to see the development of this organization. The OSIS experience taught me leadership and teamwork.",
      "OSIS Armata has shaped my character to be more responsible and caring towards others. Thank you for all the valuable experiences.",
      "Being part of OSIS Armata is a special pride. This organization teaches noble values and the spirit of cooperation.",
    ],
  },
}
